pipeline:
  name: bank-of-anthos
  identifier: bankofanthos
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy BoA
        identifier: Deploy_BoA
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: harnessdevenv
            deployToAll: false
            provisioner:
              steps:
                - step:
                    type: TerraformPlan
                    name: boaplan
                    identifier: boaplan
                    timeout: 10m
                    spec:
                      provisionerIdentifier: qa123
                      cloudCliConfiguration:
                        command: Apply
                        configFiles:
                          store:
                            spec:
                              connectorRef: tmmfcs
                              gitFetchType: Branch
                              branch: main
                              folderPath: iac/tmm-gcp
                            type: Github
                - step:
                    type: TerraformApply
                    name: apply
                    identifier: apply
                    timeout: 25m
                    spec:
                      provisionerIdentifier: qa123
                      cloudCliConfiguration:
                        spec:
                          configFiles:
                            store:
                              spec:
                                connectorRef: tmmfcs
                                gitFetchType: Branch
                                branch: main
                                folderPath: iac/tmm-gcp
                              type: Github
              rollbackSteps:
                - step:
                    type: TerraformRollback
                    name: rollback
                    identifier: rollback
                    timeout: 10m
                    spec:
                      provisionerIdentifier: qa123
                      skipRefreshCommand: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfra
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDeployment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 25m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: 1
                          skipDryRun: false
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 25m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDeployment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 25m
                        spec:
                          skipDryRun: false
                          pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
          service:
            serviceRef: boa
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        timeout: 25m
